### ISSUE TITLE
Compute total result for each submission file

### ISSUE THREAD

**Issue by shakram02** [CC451-Computer-Networks-TA-team/GraderX-BE#42]
Total result depends on the files in contained in the student submission's directory.

Example directory structure
```
submissions
|- 3031
      |-> 3031_lab1.c
      |-> 3031_lab1_stdout_1.txt
      |-> 3031_lab1_stdout_2.txt
      |-> 3031_lab1_stdout_3.txt
      |-> 3031_lab1_results.txt
|- 3192
      |-> 3192_lab1.c
      |-> 3192_lab1_stdout_1.txt
      |-> 3192_lab1_stdout_2.txt
      |-> 3192_lab1_stdout_3.txt
      |-> 3192_lab1_results.txt
```

**Comment by Hagar-Usama** [comment]
https://gist.github.com/Hagar-Usama/e23e2d1f27d76727036388b4861f17a1
@amroakmal  @amohamed97

**Comment by Hagar-Usama** [comment]
new format:
https://gist.github.com/Hagar-Usama/32ae0e69a3aa66a3f52861c21c1d7aa7

related: FE #28 

* [x] output json file (to be passed to react-diff-view)
* [x] output json file (to be passed to react-charts)
