### ISSUE TITLE
[BUG] Grader accepts invalid archives

### ISSUE THREAD

**Issue by Hagar-Usama** [CC451-Computer-Networks-TA-team/GraderX-BE#62]
#### TL;DR
see  _Demonstration_

#### Intro
The grader accepts archives that don't have submissions, and returns results

#### Behavior
* Expected
  * to reject the archive file

* Actual Behavior
  * accepts the archive file and fetches `results.txt` of the **previous** successful grading process
      
#### Demonstration
 ![download_bug](https://user-images.githubusercontent.com/34040335/90202139-15b64880-dddd-11ea-9cd9-5c08784c6310.gif)

**Comment by amohamed97** [comment]
Should be resolved with PR #63
