### ISSUE TITLE
C Grader's results fetch should use the submission key

### ISSUE THREAD

**Issue by amohamed97** [CC451-Computer-Networks-TA-team/GraderX-BE#77]
Any results-fetching related request will have a submission key with it, the c grader should take this key and fetch the requested result from the submissions directory corresponding to that key.

**Comment by Hagar-Usama** [comment]
Course
                   |-- Lab1
                           |-- key1
                                   |-- Submissions
                                      |-- id_id
                                      |-- id_id
                                   |-- results, diff, chart


                            |-- key2
                                   |-- Submissions
                                      |-- id_id
                                      |-- id_id
                                   |-- results, diff, chart
